-- 1. Références (Types)
CREATE TABLE IF NOT EXISTS `type_client` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `tenant_id` BIGINT UNSIGNED NOT NULL DEFAULT 1,
    `libelle` VARCHAR(100) NOT NULL,
    `detail` VARCHAR(255) NULL,
    `exempt_tva` TINYINT(1) DEFAULT 0,
    `vip` TINYINT(1) DEFAULT 0,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NULL,
    `deleted_at` TIMESTAMP NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `type_fournisseur` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `tenant_id` BIGINT UNSIGNED NOT NULL DEFAULT 1,
    `libelle` VARCHAR(100) NOT NULL,
    `detail` VARCHAR(255) NULL,
    `vip` TINYINT(1) DEFAULT 0,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NULL,
    `deleted_at` TIMESTAMP NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 2. Tiers (Clients)
CREATE TABLE IF NOT EXISTS `clients` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `tenant_id` BIGINT UNSIGNED NOT NULL DEFAULT 1,
    `code_client` VARCHAR(50) NOT NULL,
    `societe` VARCHAR(255) NOT NULL,
    `is_personne_physique` TINYINT(1) DEFAULT 0,
    `civilite` VARCHAR(10) NULL,
    `nom` VARCHAR(100) NULL,
    `prenom` VARCHAR(100) NULL,
    `ice` VARCHAR(100) NULL,
    `rc` VARCHAR(50) NULL,
    `if_fiscal` VARCHAR(50) NULL,
    `patente` VARCHAR(50) NULL,
    `adresse` VARCHAR(500) NULL,
    `ville` VARCHAR(100) NULL,
    `code_postal` VARCHAR(20) NULL,
    `pays` VARCHAR(100) DEFAULT 'Maroc',
    `telephone` VARCHAR(20) NULL,
    `mobile` VARCHAR(20) NULL,
    `fax` VARCHAR(20) NULL,
    `email` VARCHAR(255) NULL,
    `site_web` VARCHAR(255) NULL,
    `rib` VARCHAR(50) NULL,
    `banque` VARCHAR(100) NULL,
    `image_path` VARCHAR(500) NULL,
    `observations` LONGTEXT NULL,
    `exempt_tva` TINYINT(1) DEFAULT 0,
    `type_client_id` BIGINT UNSIGNED NULL,
    `plafond_credit` DECIMAL(24,2) DEFAULT 0.00,
    `delai_paiement` INT DEFAULT 0,
    `montant_rest_du` DECIMAL(24,2) DEFAULT 0.00,
    `commercial_id` BIGINT UNSIGNED NULL,
    `created_by` BIGINT UNSIGNED NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
    `is_active` TINYINT(1) DEFAULT 1,
    `deleted_at` TIMESTAMP NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_tenant_code_client` (`tenant_id`, `code_client`),
    KEY `idx_societe_cli` (`societe`),
    CONSTRAINT `fk_client_type` FOREIGN KEY (`type_client_id`) REFERENCES `type_client`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 3. Tiers (Fournisseurs)
CREATE TABLE IF NOT EXISTS `fournisseurs` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `tenant_id` BIGINT UNSIGNED NOT NULL DEFAULT 1,
    `code_fournisseur` VARCHAR(50) NOT NULL,
    `societe` VARCHAR(255) NOT NULL,
    `is_personne_physique` TINYINT(1) DEFAULT 0,
    `civilite` VARCHAR(10) NULL,
    `nom` VARCHAR(100) NULL,
    `prenom` VARCHAR(100) NULL,
    `ice` VARCHAR(100) NULL,
    `rc` VARCHAR(50) NULL,
    `if_fiscal` VARCHAR(50) NULL,
    `patente` VARCHAR(50) NULL,
    `adresse` VARCHAR(500) NULL,
    `ville` VARCHAR(100) NULL,
    `code_postal` VARCHAR(20) NULL,
    `pays` VARCHAR(100) DEFAULT 'Maroc',
    `telephone` VARCHAR(20) NULL,
    `mobile` VARCHAR(20) NULL,
    `fax` VARCHAR(20) NULL,
    `email` VARCHAR(255) NULL,
    `site_web` VARCHAR(255) NULL,
    `rib` VARCHAR(50) NULL,
    `banque` VARCHAR(100) NULL,
    `image_path` VARCHAR(500) NULL,
    `observations` LONGTEXT NULL,
    `type_fournisseur_id` BIGINT UNSIGNED NULL,
    `delai_livraison` INT DEFAULT 0,
    `created_by` BIGINT UNSIGNED NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
    `is_active` TINYINT(1) DEFAULT 1,
    `deleted_at` TIMESTAMP NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_tenant_code_fourn` (`tenant_id`, `code_fournisseur`),
    KEY `idx_societe_fourn` (`societe`),
    CONSTRAINT `fk_fourn_type` FOREIGN KEY (`type_fournisseur_id`) REFERENCES `type_fournisseur`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 4. Tables Liées
CREATE TABLE IF NOT EXISTS `contacts` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `tenant_id` BIGINT UNSIGNED NOT NULL DEFAULT 1,
    `contactable_type` VARCHAR(100) NOT NULL,
    `contactable_id` BIGINT UNSIGNED NOT NULL,
    `nom` VARCHAR(100) NOT NULL,
    `prenom` VARCHAR(100) NULL,
    `fonction` VARCHAR(100) NULL,
    `email` VARCHAR(255) NULL,
    `telephone` VARCHAR(20) NULL,
    `mobile` VARCHAR(20) NULL,
    `is_principal` TINYINT(1) DEFAULT 0,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NULL,
    `deleted_at` TIMESTAMP NULL,
    PRIMARY KEY (`id`),
    KEY `idx_contactable` (`contactable_type`, `contactable_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `adresses_livraison` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `tenant_id` BIGINT UNSIGNED NOT NULL DEFAULT 1,
    `client_id` BIGINT UNSIGNED NOT NULL,
    `adresse` VARCHAR(500) NOT NULL,
    `ville` VARCHAR(100) NULL,
    `code_postal` VARCHAR(20) NULL,
    `pays` VARCHAR(100) NULL,
    `contact` VARCHAR(100) NULL,
    `telephone` VARCHAR(20) NULL,
    `observations` TEXT NULL,
    `is_default` TINYINT(1) DEFAULT 0,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NULL,
    `deleted_at` TIMESTAMP NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `fk_adr_liv_client` FOREIGN KEY (`client_id`) REFERENCES `clients`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
