-- ============================================================
-- GenyCom Web SaaS — Cycle de Vente (Devis, Factures, BL, Avoirs)
-- ============================================================

-- Projets
CREATE TABLE IF NOT EXISTS `projets` (
    `id`                BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `code_projet`       VARCHAR(50) NOT NULL,
    `nom_projet`        VARCHAR(255) NOT NULL,
    `description`       LONGTEXT NULL,
    `client_id`         BIGINT UNSIGNED NULL,
    `date_debut`        DATE NULL,
    `date_fin_prevue`   DATE NULL,
    `date_fin_reelle`   DATE NULL,
    `budget_prevu`      DECIMAL(24,2) DEFAULT 0.00,
    `budget_consomme`   DECIMAL(24,2) DEFAULT 0.00,
    `statut`            ENUM('brouillon','en_cours','en_pause','termine','annule') DEFAULT 'brouillon',
    `responsable_id`    BIGINT UNSIGNED NULL,
    `priorite`          ENUM('basse','normale','haute','urgente') DEFAULT 'normale',
    `created_by`        BIGINT UNSIGNED NULL,
    `created_at`        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at`        TIMESTAMP NULL,
    `deleted_at`        TIMESTAMP NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_code_projet` (`code_projet`),
    FOREIGN KEY (`client_id`) REFERENCES `clients`(`id`),
    FOREIGN KEY (`responsable_id`) REFERENCES `users`(`id`),
    FOREIGN KEY (`created_by`) REFERENCES `users`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Devis
CREATE TABLE IF NOT EXISTS `devis` (
    `id`                BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `numero`            VARCHAR(150) NULL,
    `date_devis`        DATE NOT NULL,
    `date_validite`     DATE NULL,
    `client_id`         BIGINT UNSIGNED NOT NULL,
    `projet_id`         BIGINT UNSIGNED NULL,
    `numero_bon_commande` VARCHAR(150) NULL,
    `total_ht`          DECIMAL(24,2) DEFAULT 0.00,
    `total_tva`         DECIMAL(24,2) DEFAULT 0.00,
    `total_ttc`         DECIMAL(24,2) DEFAULT 0.00,
    `total_remise`      DECIMAL(24,2) DEFAULT 0.00,
    `etat_id`           BIGINT UNSIGNED NULL,
    `observations`      LONGTEXT NULL,
    `conditions`        LONGTEXT NULL,
    `est_facture`       TINYINT(1) DEFAULT 0,
    `est_livre`         TINYINT(1) DEFAULT 0,
    `devise_id`         BIGINT UNSIGNED NULL,
    `created_by`        BIGINT UNSIGNED NULL,
    `created_at`        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at`        TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at`        TIMESTAMP NULL,
    PRIMARY KEY (`id`),
    KEY `idx_numero` (`numero`),
    KEY `idx_client` (`client_id`),
    FOREIGN KEY (`client_id`) REFERENCES `clients`(`id`),
    FOREIGN KEY (`projet_id`) REFERENCES `projets`(`id`),
    FOREIGN KEY (`etat_id`) REFERENCES `etat_document`(`id`),
    FOREIGN KEY (`devise_id`) REFERENCES `devise`(`id`),
    FOREIGN KEY (`created_by`) REFERENCES `users`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ligne_devis` (
    `id`                BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `devis_id`          BIGINT UNSIGNED NOT NULL,
    `produit_id`        BIGINT UNSIGNED NULL,
    `designation`       VARCHAR(255) NOT NULL,
    `description`       TEXT NULL,
    `quantite`          DECIMAL(24,2) DEFAULT 1.00,
    `unite`             VARCHAR(50) NULL,
    `prix_unitaire`     DECIMAL(24,4) DEFAULT 0.0000,
    `taux_tva`          DECIMAL(5,3) DEFAULT 0.000,
    `remise_pourcent`   DECIMAL(5,2) DEFAULT 0.00,
    `remise_montant`    DECIMAL(24,2) DEFAULT 0.00,
    `montant_ht`        DECIMAL(24,2) DEFAULT 0.00,
    `montant_tva`       DECIMAL(24,2) DEFAULT 0.00,
    `montant_ttc`       DECIMAL(24,2) DEFAULT 0.00,
    `ordre`             SMALLINT DEFAULT 0,
    `is_produit_fini`   TINYINT(1) DEFAULT 0,
    `created_at`        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at`        TIMESTAMP NULL,
    PRIMARY KEY (`id`),
    FOREIGN KEY (`devis_id`) REFERENCES `devis`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`produit_id`) REFERENCES `produits`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Factures Client
CREATE TABLE IF NOT EXISTS `factures` (
    `id`                    BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `numero`                VARCHAR(150) NULL,
    `date_facture`          DATE NOT NULL,
    `date_echeance`         DATE NULL,
    `client_id`             BIGINT UNSIGNED NOT NULL,
    `projet_id`             BIGINT UNSIGNED NULL,
    `devis_id`              BIGINT UNSIGNED NULL,
    `total_ht`              DECIMAL(24,2) DEFAULT 0.00,
    `total_tva`             DECIMAL(24,2) DEFAULT 0.00,
    `total_ttc`             DECIMAL(24,2) DEFAULT 0.00,
    `total_remise`          DECIMAL(24,2) DEFAULT 0.00,
    `montant_regle`         DECIMAL(24,2) DEFAULT 0.00,
    `montant_restant`       DECIMAL(24,2) DEFAULT 0.00,
    `etat_id`               BIGINT UNSIGNED NULL,
    `condition_reglement_id` BIGINT UNSIGNED NULL,
    `mode_reglement_id`     BIGINT UNSIGNED NULL,
    `est_reglee`            TINYINT(1) DEFAULT 0,
    `date_reglement`        DATE NULL,
    `observations`          LONGTEXT NULL,
    `devise_id`             BIGINT UNSIGNED NULL,
    `created_by`            BIGINT UNSIGNED NULL,
    `created_at`            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at`            TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at`            TIMESTAMP NULL,
    PRIMARY KEY (`id`),
    KEY `idx_numero` (`numero`),
    KEY `idx_client` (`client_id`),
    KEY `idx_etat` (`etat_id`),
    FOREIGN KEY (`client_id`) REFERENCES `clients`(`id`),
    FOREIGN KEY (`projet_id`) REFERENCES `projets`(`id`),
    FOREIGN KEY (`devis_id`) REFERENCES `devis`(`id`),
    FOREIGN KEY (`etat_id`) REFERENCES `etat_document`(`id`),
    FOREIGN KEY (`condition_reglement_id`) REFERENCES `condition_reglement`(`id`),
    FOREIGN KEY (`mode_reglement_id`) REFERENCES `mode_reglement`(`id`),
    FOREIGN KEY (`devise_id`) REFERENCES `devise`(`id`),
    FOREIGN KEY (`created_by`) REFERENCES `users`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ligne_facture` (
    `id`                BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `facture_id`        BIGINT UNSIGNED NOT NULL,
    `produit_id`        BIGINT UNSIGNED NULL,
    `designation`       VARCHAR(255) NOT NULL,
    `description`       TEXT NULL,
    `quantite`          DECIMAL(24,2) DEFAULT 1.00,
    `unite`             VARCHAR(50) NULL,
    `prix_unitaire`     DECIMAL(24,4) DEFAULT 0.0000,
    `taux_tva`          DECIMAL(5,3) DEFAULT 0.000,
    `remise_pourcent`   DECIMAL(5,2) DEFAULT 0.00,
    `remise_montant`    DECIMAL(24,2) DEFAULT 0.00,
    `montant_ht`        DECIMAL(24,2) DEFAULT 0.00,
    `montant_tva`       DECIMAL(24,2) DEFAULT 0.00,
    `montant_ttc`       DECIMAL(24,2) DEFAULT 0.00,
    `ordre`             SMALLINT DEFAULT 0,
    `source_type`       VARCHAR(50) DEFAULT 'saisie_manuelle',
    `is_produit_fini`   TINYINT(1) DEFAULT 0,
    `created_at`        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at`        TIMESTAMP NULL,
    `deleted_at`        TIMESTAMP NULL,
    PRIMARY KEY (`id`),
    FOREIGN KEY (`facture_id`) REFERENCES `factures`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`produit_id`) REFERENCES `produits`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Bons de livraison
CREATE TABLE IF NOT EXISTS `bons_livraison` (
    `id`                BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `numero`            VARCHAR(150) NULL,
    `date_livraison`    DATE NOT NULL,
    `devis_id`          BIGINT UNSIGNED NULL,
    `facture_id`        BIGINT UNSIGNED NULL,
    `client_id`         BIGINT UNSIGNED NOT NULL,
    `adresse_livraison_id` BIGINT UNSIGNED NULL,
    `mode_livraison_id` BIGINT UNSIGNED NULL,
    `observations`      LONGTEXT NULL,
    `statut`            ENUM('brouillon','valide','livre','annule') DEFAULT 'brouillon',
    `created_by`        BIGINT UNSIGNED NULL,
    `created_at`        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at`        TIMESTAMP NULL,
    `deleted_at`        TIMESTAMP NULL,
    PRIMARY KEY (`id`),
    FOREIGN KEY (`devis_id`) REFERENCES `devis`(`id`),
    FOREIGN KEY (`facture_id`) REFERENCES `factures`(`id`),
    FOREIGN KEY (`client_id`) REFERENCES `clients`(`id`),
    FOREIGN KEY (`created_by`) REFERENCES `users`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ligne_bon_livraison` (
    `id`                BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `bon_livraison_id`  BIGINT UNSIGNED NOT NULL,
    `produit_id`        BIGINT UNSIGNED NOT NULL,
    `designation`       VARCHAR(255) NOT NULL,
    `quantite_prevue`   DECIMAL(24,2) DEFAULT 0.00,
    `quantite_livree`   DECIMAL(24,2) DEFAULT 0.00,
    `ordre`             SMALLINT DEFAULT 0,
    `created_at`        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at`        TIMESTAMP NULL,
    PRIMARY KEY (`id`),
    FOREIGN KEY (`bon_livraison_id`) REFERENCES `bons_livraison`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`produit_id`) REFERENCES `produits`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Avoirs Client
CREATE TABLE IF NOT EXISTS `avoirs_client` (
    `id`                    BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `numero`                VARCHAR(150) NULL,
    `date_avoir`            DATE NOT NULL,
    `client_id`             BIGINT UNSIGNED NOT NULL,
    `facture_id`            BIGINT UNSIGNED NULL,
    `total_ht`              DECIMAL(24,2) DEFAULT 0.00,
    `total_tva`             DECIMAL(24,2) DEFAULT 0.00,
    `total_ttc`             DECIMAL(24,2) DEFAULT 0.00,
    `etat_id`               BIGINT UNSIGNED NULL,
    `montant_regle`         DECIMAL(24,2) DEFAULT 0.00,
    `est_reglee`            TINYINT(1) DEFAULT 0,
    `motif`                 VARCHAR(500) NULL,
    `observations`          LONGTEXT NULL,
    `created_by`            BIGINT UNSIGNED NULL,
    `created_at`            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at`            TIMESTAMP NULL,
    `deleted_at`            TIMESTAMP NULL,
    PRIMARY KEY (`id`),
    FOREIGN KEY (`client_id`) REFERENCES `clients`(`id`),
    FOREIGN KEY (`facture_id`) REFERENCES `factures`(`id`),
    FOREIGN KEY (`etat_id`) REFERENCES `etat_document`(`id`),
    FOREIGN KEY (`created_by`) REFERENCES `users`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ligne_avoir_client` (
    `id`                BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `avoir_id`          BIGINT UNSIGNED NOT NULL,
    `produit_id`        BIGINT UNSIGNED NULL,
    `designation`       VARCHAR(255) NOT NULL,
    `quantite`          DECIMAL(24,2) DEFAULT 1.00,
    `prix_unitaire`     DECIMAL(24,4) DEFAULT 0.0000,
    `taux_tva`          DECIMAL(5,3) DEFAULT 0.000,
    `montant_ht`        DECIMAL(24,2) DEFAULT 0.00,
    `montant_tva`       DECIMAL(24,2) DEFAULT 0.00,
    `montant_ttc`       DECIMAL(24,2) DEFAULT 0.00,
    `ordre`             SMALLINT DEFAULT 0,
    `created_at`        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at`        TIMESTAMP NULL,
    PRIMARY KEY (`id`),
    FOREIGN KEY (`avoir_id`) REFERENCES `avoirs_client`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`produit_id`) REFERENCES `produits`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

